/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Maxime' at '3/11/16 18:55' with Gradle 2.11
 *
 * @author Maxime, @date 3/11/16 18:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
